Start exhaustive testing of package DBs
This is not much more than a skeleton at the moment, and it doesn't work
because of

    ERROR: .: canonicalizePath: resource exhausted (Too many open files)

Note yet sure what's causing that.